---
- name: Run a Docker container with parameters
  hosts: all
  become: true

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Docker container with env vars
      community.docker.docker_container:
        name: solr
        image: "{{ docker_image }}"
        #env:
        #  SOLR_OPTS: "{{ solr_opts }}"
        #  SOLR_JAVA_MEM: "{{ solr_java_mem }}"
        state: started
        volumes:
          - "solr-volume:/var/solr"
        ports:
          - "8983:8983"
        restart_policy: unless-stopped