---
- name: Attach and mount EBS volume with setup
  hosts: all
  #hosts: i-0f76776b9ba41a172
  gather_facts: false
  collections:
    - amazon.aws
  become: true

  vars:
    region: ca-central-1
    device_name: /dev/xvdf
    volume_tag_name: "true"
    ebs_mount_point: /mnt/data
    ebs_device_name: "{{ device_name }}"
    docker_image: "solr:latest"

  pre_tasks: 
    - import_tasks: aws/install-ansible-collection-amazon.yml
    - import_tasks: aws/auto-attach-ec2-ebs.yml

  tasks:
    - import_tasks: general/install-docker.yml
    - import_tasks: aws/deploy-solr.yml